name: archlinux-pi Raspberry Pi 4

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build:
    name: archlinux-pi Raspberry Pi 4 Image
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: set-vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm

      - name: Build archlinux-pi-rp4.img
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build archlinux-pi-rp4.json

      - name: Compress output
        run: sudo xz -9 archlinux-pi-rp4.img

      - name: Remove release
        uses: kopp/action-delete-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest

      - name: Upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          name: archlinux-pi ${{ github.run_number }} from ${{ steps.set-vars.outputs.date }}
          body: |
            To use this package, please `unxz archlinux-pi-rp4.img.xz` then `dd` to an SD card device.
          files: |
            archlinux-pi-rp4.img.xz
          draft: false
          prerelease: false
